### PR TITLE
Add mongoose persistence adapter

### PR DESCRIPTION
**Pull request by phiros**
This PR allows strider to be used in conjunction with mongodb (using mongoose).
The changes are based on #19 

@knownasilya I thought it would be straight-forward to port the existing persistence interface (simple-collection) to mongoose. However, I discovered that mongoose behaves quite different from loki in
some regards. A big problem I noticed was that if I update models with nested objects the nested object will be completely overwritten.
For example a job has a property called `children`. The object is structured like this:

``` javascript
 {
  <database id of the child>: {
     status: <string>
     result: <string>
     updatedAt: <number>
     ...
  }
  <database id of another child>: {
     status: <string>
     result: <string>
     updatedAt: <number>
     ...
  }
}
```

In loki a child job can be easily added to this property by doing the following (pseudo code):

``` javascript
var job = fetchJob()
job.children[<database id of a third child>] =  {
   status: <string>
   result: <string>
   updatedAt: <number>
   ...
}
Job.update(job.id, job)
```

However, with mongoose this does not work (the property will be completely overwritten with the last update; adding children is not possible). I am unsure on how to fix this without breaking the existing interface (simple-collection). Could you help me with this one? 

In case you want to run core, drone and client:

For core (note: you can run the tests in same way; also: in order to use Loki just set `STRIDER_DB_TYPE` to something other than mongodb): 

```
~/core $ STRIDER_MONGODB_URI=mongodb://localhost:27017/somedb STRIDER_DB_TYPE=mongodb STRIDER_CLEAR_DB=true npm start
```

For drone:

```
~/drone $ CORE_URL=http://localhost:8000 CORE_ADMIN_USER=admin CORE_ADMIN_PWD=admin ./initDrone.sh
```

For client:

```
~/client $ ember s
```

### CODE REVIEW

**Comment by phiros** [comment]
BTW: In order to create actual child jobs you can use (both core and at least one drone needs to run for this): 

```
~/inject-github-pr $ node inject-github-pr 
```

Repo: https://github.com/phiros/inject-github-pr

**Comment by phiros** [comment]
@knownasilya I fixed the issue. Accessing /api/v1/projects/<id>/jobs or /api/v1/projects/<id>/jobs/id/<id>
now causes the event handlers for these routes to fetch the jobs and optionally their child jobs (if they exist). That seems to work quite fine now (even though this solution uses (1+n) queries; One for the job or list of jobs and an additional query to find the child jobs for each job).

**Comment by phiros** [comment]
See #19: I'll merge both PRs. Dealing with many dependant PRs is a little bit cumbersome.

**Comment by knownasilya** [comment]
Thanks. I'm currently tied up with work.

**Pull request merged**
